import glob
file_list = glob.glob('*.cpp')


subdirs = Split("""
boards
drivers/common
fir
input
utils
""")
#palettes

Import('env')
Export('env')

if env['LUA']:
  file_list.append('lua-engine.cpp')
  if env['SYSTEM_LUA'] == 0:
    subdirs.append('lua')

if env['CREATE_AVI']:
  subdirs.append('drivers/videolog')
  


print env['LINKFLAGS']

if env['PLATFORM'] == 'win32':
  fceux = env.Program('fceux.exe', file_list)
else:
  fceux = env.Program('fceux', file_list)
Return('fceux')
